- name: "Setting fact for juseppe_plugins"
  set_fact:
    juseppe_plugins: []

- name: "Setting fact for juseppe_plugins -> wizard plugins"
  set_fact:
      juseppe_plugins: "{{ cj_wizard_plugins }}"
  when: (cj_wizard is defined ) and (cj_wizard | bool)

- name: "merge plugin lists -> jenkins theme"
  set_fact:
    juseppe_plugins: "{{ juseppe_plugins + cj_theme_plugins }}"
  when: (cj_theme is defined) and (cj_theme | bool)