---
- name: "Cleanup"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ cj_home }}"
  - "{{ cj_log_dir }}"
  - "{{ cj_cache_dir }}"
  - "{{ cj_uc_json }}"
  tags:
  - cleanup

- name: "Stop jenkins"
  service:
    name: jenkins
    state: stopped
    enabled: no

- name: "Remove jenkins package"
  package:
    name: jenkins
    state: absent
  tags:
  - cleanup
