---
- name: "Create Jenkins init script dir"
  file:
    path: "{{ cj_home }}/init.groovy.d"
    state: directory
    owner:  "{{ cj_runas_user }}"
    group:  "{{ cj_runas_group }}"
    mode: 0755

- name: "Generate groovy script for jenkins bootstrap execution"
  template:
    src: "{{ item }}.j2"
    dest: "{{ cj_init_dir }}/{{ item }}"
    owner:  "{{ cj_runas_user }}"
    group:  "{{ cj_runas_group }}"
  with_items:
    - init_config.groovy

- name: "Deploy GitHub connection config"
  template:
    src: "{{ item }}.j2"
    dest: "{{ cj_home }}/{{ item }}"
  with_items:
  - "org.jenkinsci.plugins.ghprb.GhprbTrigger.xml"

- include: cj-restart-jenkins.yml
