---
- name: "Setting fact for cj_plugins"
  set_fact:
    cj_plugins: []

- name: "Setting fact for cj_plugins -> wizard plugins"
  set_fact:
      cj_plugins: "{{ cj_wizard_plugins }}"
  when: (cj_wizard is defined ) and (cj_wizard | bool)

- name: "merge plugin lists -> jenkins theme"
  set_fact:
    cj_plugins: "{{ cj_plugins + cj_theme_plugins }}"
  when: (cj_theme is defined) and (cj_theme | bool)