---
- hosts: jenkins-server
  tasks:
    - name: "Network vars"
      set_fact:
        nexus_hostname: "{{ hostvars[groups['nexus-server'][0]]['ansible_host'] }}"
        cj_jenkins_hostname: "{{ hostvars[groups['jenkins-server'][0]]['ansible_host'] }}"
        gitlab_hostname: "{{ hostvars[groups['gitlab-server'][0]]['ansible_host'] }}"

- hosts: jenkins-server
  vars:
    cj_nexus: false
  roles:
  - java
  - simple-docker-daemon
  - juseppe
  - jenkins
